name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build 
      uses: docker/build-push-action@v6
      with:
          context: .
          push: false
          tags: user/app:latest

    - name: Push
      uses: docker/build-push-action@v6
      with:
          context: .
          push: true
          tags: user/app:latest
